/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopRouteImport } from './routes/top'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackageNameRouteImport } from './routes/package/$name'
import { Route as ApiSentryRouteImport } from './routes/api/sentry'

const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageNameRoute = PackageNameRouteImport.update({
  id: '/package/$name',
  path: '/package/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryRoute = ApiSentryRouteImport.update({
  id: '/api/sentry',
  path: '/api/sentry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/top': typeof TopRoute
  '/api/sentry': typeof ApiSentryRoute
  '/package/$name': typeof PackageNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/top': typeof TopRoute
  '/api/sentry': typeof ApiSentryRoute
  '/package/$name': typeof PackageNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/top': typeof TopRoute
  '/api/sentry': typeof ApiSentryRoute
  '/package/$name': typeof PackageNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/top' | '/api/sentry' | '/package/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/top' | '/api/sentry' | '/package/$name'
  id: '__root__' | '/' | '/about' | '/top' | '/api/sentry' | '/package/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TopRoute: typeof TopRoute
  ApiSentryRoute: typeof ApiSentryRoute
  PackageNameRoute: typeof PackageNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$name': {
      id: '/package/$name'
      path: '/package/$name'
      fullPath: '/package/$name'
      preLoaderRoute: typeof PackageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry': {
      id: '/api/sentry'
      path: '/api/sentry'
      fullPath: '/api/sentry'
      preLoaderRoute: typeof ApiSentryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TopRoute: TopRoute,
  ApiSentryRoute: ApiSentryRoute,
  PackageNameRoute: PackageNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
